In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("survey_results_public.csv", low_memory=False)
schema = pd.read_csv("survey_results_schema.csv")

In [3]:
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [5]:
list(df.columns)

['ResponseId',
 'MainBranch',
 'Age',
 'EdLevel',
 'Employment',
 'EmploymentAddl',
 'WorkExp',
 'LearnCodeChoose',
 'LearnCode',
 'LearnCodeAI',
 'AILearnHow',
 'YearsCode',
 'DevType',
 'OrgSize',
 'ICorPM',
 'RemoteWork',
 'PurchaseInfluence',
 'TechEndorseIntro',
 'TechEndorse_1',
 'TechEndorse_2',
 'TechEndorse_3',
 'TechEndorse_4',
 'TechEndorse_5',
 'TechEndorse_6',
 'TechEndorse_7',
 'TechEndorse_8',
 'TechEndorse_9',
 'TechEndorse_13',
 'TechEndorse_13_TEXT',
 'TechOppose_1',
 'TechOppose_2',
 'TechOppose_3',
 'TechOppose_5',
 'TechOppose_7',
 'TechOppose_9',
 'TechOppose_11',
 'TechOppose_13',
 'TechOppose_16',
 'TechOppose_15',
 'TechOppose_15_TEXT',
 'Industry',
 'JobSatPoints_1',
 'JobSatPoints_2',
 'JobSatPoints_3',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'JobSatPoints_13',
 'JobSatPoints_14',
 'JobSatPoints_15',
 'JobSatPoints_16',
 'JobSatPoints_15_TEXT',
 'AIThreat',
 'NewRole',
 'ToolCountWork',
 'ToolCountPersonal',
 'Country',
 'Currency',
 'CompTotal',
 'LanguageChoice',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LanguageAdmired',
 'LanguagesHaveEntry',
 'LanguagesWantEntry',
 'DatabaseChoice',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DatabaseAdmired',
 'DatabaseHaveEntry',
 'DatabaseWantEntry',
 'PlatformChoice',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PlatformAdmired',
 'PlatformHaveEntry',
 'PlatformWantEntry',
 'WebframeChoice',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WebframeAdmired',
 'WebframeHaveEntry',
 'WebframeWantEntry',
 'DevEnvsChoice',
 'DevEnvsHaveWorkedWith',
 'DevEnvsWantToWorkWith',
 'DevEnvsAdmired',
 'DevEnvHaveEntry',
 'DevEnvWantEntry',
 'SOTagsHaveWorkedWith',
 'SOTagsWantToWorkWith',
 'SOTagsAdmired',
 'SOTagsHaveEntry',
 'SOTagsWant Entry',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OfficeStackAsyncAdmired',
 'OfficeStackHaveEntry',
 'OfficeStackWantEntry',
 'CommPlatformHaveWorkedWith',
 'CommPlatformWantToWorkWith',
 'CommPlatformAdmired',
 'CommPlatformHaveEntr',
 'CommPlatformWantEntr',
 'AIModelsChoice',
 'AIModelsHaveWorkedWith',
 'AIModelsWantToWorkWith',
 'AIModelsAdmired',
 'AIModelsHaveEntry',
 'AIModelsWantEntry',
 'SOAccount',
 'SOVisitFreq',
 'SODuration',
 'SOPartFreq',
 'SO_Dev_Content',
 'SO_Actions_1',
 'SO_Actions_16',
 'SO_Actions_3',
 'SO_Actions_4',
 'SO_Actions_5',
 'SO_Actions_6',
 'SO_Actions_9',
 'SO_Actions_7',
 'SO_Actions_10',
 'SO_Actions_15',
 'SO_Actions_15_TEXT',
 'SOComm',
 'SOFriction',
 'AISelect',
 'AISent',
 'AIAcc',
 'AIComplex',
 'AIToolCurrently partially AI',
 "AIToolDon't plan to use AI for this task",
 'AIToolPlan to partially use AI',
 'AIToolPlan to mostly use AI',
 'AIToolCurrently mostly AI',
 'AIFrustration',
 'AIExplain',
 'AIAgents',
 'AIAgentChange',
 'AIAgent_Uses',
 'AgentUsesGeneral',
 'AIAgentImpactSomewhat agree',
 'AIAgentImpactNeutral',
 'AIAgentImpactSomewhat disagree',
 'AIAgentImpactStrongly agree',
 'AIAgentImpactStrongly disagree',
 'AIAgentChallengesNeutral',
 'AIAgentChallengesSomewhat disagree',
 'AIAgentChallengesStrongly agree',
 'AIAgentChallengesSomewhat agree',
 'AIAgentChallengesStrongly disagree',
 'AIAgentKnowledge',
 'AIAgentKnowWrite',
 'AIAgentOrchestration',
 'AIAgentOrchWrite',
 'AIAgentObserveSecure',
 'AIAgentObsWrite',
 'AIAgentExternal',
 'AIAgentExtWrite',
 'AIHuman',
 'AIOpen',
 'ConvertedCompYearly',
 'JobSat']

In [6]:
schema.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

Завдання 1. Підрахунок загальної кількості респондентів

In [7]:
total_respondents = df.shape[0]
total_respondents

49191

Завдання 2. Аналіз повноти відповідей респондентів

In [8]:
questions = set(schema["qname"])
columns = set(df.columns)
valid_questions = list(questions.intersection(columns))
respondents_full = df[valid_questions].notna().all(axis=1).sum()
respondents_full

np.int64(0)

Завдання 3. Статистичний аналіз досвіду респондентів

In [9]:
mean_exp = df["WorkExp"].mean()
median_exp = df["WorkExp"].median()
mode_exp = df["WorkExp"].mode()[0]
pd.Series({
    "Mean":mean_exp,
    "Median":median_exp,
    "Mode":mode_exp
})

Mean      13.367403
Median    10.000000
Mode      10.000000
dtype: float64

Завдання 4. Аналіз віддаленої роботи

In [10]:
df["RemoteWork"].value_counts()

RemoteWork
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [11]:
remote_workers = df[df["RemoteWork"] == "Remote"].shape[0]
remote_workers

10931

Завдання 5. Визначення популярності Python

In [12]:
python_users = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)

python_percent = python_users.mean() * 100

print(f"{python_percent:.2f}%")

37.54%

Завдання 6. Аналіз шляхів навчання програмуванню

In [13]:
online_learners = df["LearnCode"].str.contains("Online", na=False).sum()
online_learners

np.int64(10973)

Завдання 7. Географічний аналіз компенсації Python-розробників

In [14]:
python_dev = df[df["LanguageHaveWorkedWith"].str.contains("Python", na=False)]
python_dev = python_dev.dropna(subset=["ConvertedCompYearly"])
salary_stats = (
    python_dev
    .groupby("Country")["ConvertedCompYearly"]
    .agg(
        mean_salary="mean",
        median_salary="median"
    )
    .round(2)
)
salary_stats

                                      mean_salary  median_salary
Country
Afghanistan                              22328.67         1000.0
Albania                                  47217.60        50000.0
Algeria                                  20187.29         7088.0
Andorra                                 226103.50       226103.5
Antigua and Barbuda                          1.00            1.0
...                                           ...            ...
Venezuela, Bolivarian Republic of...      9908.65         3000.0
Viet Nam                                218837.17         8254.0
Yemen                                    32929.50        23672.0
Zambia                                    5424.25         3206.0
Zimbabwe                                 34000.00        25500.0

[153 rows x 2 columns]

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [15]:
top5 = df.sort_values("ConvertedCompYearly", ascending=False).head(5)
top5[["EdLevel","ConvertedCompYearly"]]

                                               EdLevel  ConvertedCompYearly
34267              Associate degree (A.A., A.S., etc.)           50000000.0
28700  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           33552715.0
43143              Associate degree (A.A., A.S., etc.)           18387548.0
35353     Bachelor’s degree (B.A., B.S., B.Eng., etc.)           15430267.0
45971  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           13921760.0

*Завдання 9. Аналіз популярності Python по віковим категоріям

In [16]:
df["PythonUser"] = df["LanguageHaveWorkedWith"].str.contains("Python", na=False)
age_python = (
    df.groupby("Age")["PythonUser"]
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)
age_python

                 Age  PythonUser
0    18-24 years old       40.00
1    25-34 years old       36.94
2    35-44 years old       36.72
3    45-54 years old       38.63
4    55-64 years old       37.24
5  65 years or older       31.63
6  Prefer not to say       31.22

*Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [17]:
salary_q75 = df["ConvertedCompYearly"].quantile(0.75)
top_remote = df[
    (df["ConvertedCompYearly"] > salary_q75) &
    (df["RemoteWork"] == "Remote")
]
industry_counts = (
    top_remote["Industry"]
    .value_counts()
)
industry_counts

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64